### ISSUE TITLE
For short input, refinement function throws an error

### ISSUE THREAD

**Issue by jaredchandler** [vs-uulm/nemesys#22]
When given small (short) input such as these 10 messages...

```
00000A41
00002934
00005984
000039CB
000021CA
0000486A
00002779
00005374
00004535
000051C1
```
The refinement function throws an error.
```
Traceback (most recent call last):
  File "nemesys.py", line 52, in <module>
    refinedPerMsg = refinements(segmentsPerMsg, unused=None)
  File "/content/nemesys/src/nemere/inference/segmentHandler.py", line 272, in refinements
    return nemetylRefinements(segmentsPerMsg)
  File "/content/nemesys/src/nemere/inference/segmentHandler.py", line 332, in nemetylRefinements
    splitfixed = refine.SplitFixed(charmerged).split(0, 1)
  File "/content/nemesys/src/nemere/inference/formatRefinement.py", line 610, in split
    selSeg = self.segments[segmentID]
IndexError: list index out of range
````

**Comment by qingkaishi** [comment]
any suggestions to fix the issue? I also got the exception.

**Comment by qingkaishi** [comment]
[patch.zip](https://github.com/vs-uulm/nemesys/files/8336990/patch.zip)

I use this patch to work around. Hope it can help before the official fixes.

**Comment by skleber** [comment]
There have been several code changes that solve this issue as far as I can see. I added an unittest to verify this here: 
tests/process_overall.py
