### ISSUE TITLE
hi,I have encountered a problem，and how to solve this problem

### ISSUE THREAD

**Issue by aoaowu** [vs-uulm/nemesys#25]
Load messages...
Segment messages...
Segmentation by inflections of sigma-0.6-gauss-filtered bit-variance.
Refine segmentation (NullBytes, CropChars)...
Traceback (most recent call last):
  File "nemesys.py", line 52, in <module>
    refinedPerMsg = refinements(segmentsPerMsg, unused=None)
  File "/tmp/nemesys/src/nemere/inference/segmentHandler.py", line 328, in refinements
    return zerocharPCAmocoSFrefinements(segmentsPerMsg, **kwargs)
  File "/tmp/nemesys/src/nemere/inference/segmentHandler.py", line 752, in zerocharPCAmocoSFrefinements
    pcaRound = [refine.CropChars(segs).split() for segs in zeroSlicedMessages]
  File "/tmp/nemesys/src/nemere/inference/segmentHandler.py", line 752, in <listcomp>
    pcaRound = [refine.CropChars(segs).split() for segs in zeroSlicedMessages]
  File "/tmp/nemesys/src/nemere/inference/formatRefinement.py", line 2484, in split
    from nemere.inference.fieldTypeLibrary import BinaryProtocolsFieldTypeRecognizer
ModuleNotFoundError: No module named 'nemere.inference.fieldTypeLibrary'

**Comment by skleber** [comment]
This was due to me messing up merging of branches. It should be fixed now.
